.TH Kasady 1 "November 2024" "Version 1.0" "User Commands"

.SH NAME
Kasady \- A simple viewer for PDF and PPTX files using Dear ImGui.

.SH SYNOPSIS
.B Kasady
.RI [ options ] " file"

.SH DESCRIPTION
.B Kasady
is a graphical application built with Dear ImGui for rendering and viewing PDF and PPTX files. It supports basic navigation, zooming, and fitting the content to the window.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show this help message and exit.

.TP
.B \-\-version
Show the version of the program and exit.

.TP
.B file
The path to the PDF or PPTX file to open.

.TP
.B page numbers
The number of pages to render.

.SH CONTROLS
Navigation and zooming are available via the user interface:
.IP
- Use the "Next" and "Previous" buttons to navigate between pages.
.IP
- Use the "Zoom In", "Zoom Out", and "Fit" buttons to adjust the content display.

.SH AUTHOR
Developed by [Your Name].

.SH BUGS
Report bugs to [Your Email].

.SH COPYRIGHT
Copyright © 2024 [Siddharth Karanam]. Licensed under the BSD 3 Clause.
